### ISSUE TITLE
undefined method `sortable_fields' for UserResource:Class

### ISSUE THREAD

**Issue by will3216** [superiorlu/jsonapi-swagger#1]
Seems like I am using an incompatible version of jsonapi-rails

From my Gemfile.lock
```
[...]
    jsonapi-deserializable (0.2.0)
    jsonapi-parser (0.1.1)
    jsonapi-rails (0.4.0)
      jsonapi-parser (~> 0.1.0)
      jsonapi-rb (~> 0.5.0)
    jsonapi-rb (0.5.0)
      jsonapi-deserializable (~> 0.2.0)
      jsonapi-serializable (~> 0.3.0)
    jsonapi-renderer (0.2.2)
    jsonapi-serializable (0.3.1)
      jsonapi-renderer (~> 0.2.0)
    jsonapi-swagger (0.6.0)
[...]
```

Do you know what version this gem is compatible with?

Here is the full backtrace of the error:
```
Wills-MacBook-Pro:orion Will$ bundle exec rails generate jsonapi:swagger User
Running via Spring preloader in process 15361
Traceback (most recent call last):
	52: from -e:1:in `<main>'
	51: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	50: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	49: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
	48: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	47: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
	46: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	45: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
	44: from /Users/Will/workspace/tout/orion/bin/rails:9:in `<top (required)>'
	43: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
	42: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
	41: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
	40: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	39: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require_with_bootsnap_lfi'
	38: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	37: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `block in require_with_bootsnap_lfi'
	36: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require'
	35: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/commands.rb:18:in `<top (required)>'
	34: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/command.rb:46:in `invoke'
	33: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/command/base.rb:65:in `perform'
	32: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	31: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	30: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	29: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/commands/generate/generate_command.rb:26:in `perform'
	28: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/generators.rb:276:in `invoke'
	27: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	26: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/group.rb:232:in `dispatch'
	25: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `invoke_all'
	24: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `map'
	23: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `each'
	22: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:133:in `block in invoke_all'
	21: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	20: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	19: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jsonapi-swagger-0.6.0/lib/generators/jsonapi/swagger/swagger_generator.rb:10:in `create_swagger_file'
	18: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/generators/named_base.rb:24:in `template'
	17: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/generators/named_base.rb:49:in `inside_template'
	16: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/generators/named_base.rb:25:in `block in template'
	15: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions/file_manipulation.rb:122:in `template'
	14: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions/create_file.rb:25:in `create_file'
	13: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions.rb:94:in `action'
	12: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions/create_file.rb:60:in `invoke!'
	11: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions/empty_directory.rb:115:in `invoke_with_conflict_check'
	10: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions/create_file.rb:73:in `on_conflict_behavior'
	 9: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions/create_file.rb:46:in `identical?'
	 8: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions/create_file.rb:53:in `render'
	 7: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/actions/file_manipulation.rb:131:in `block in template'
	 6: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/erb.rb:876:in `result'
	 5: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/erb.rb:876:in `eval'
	 4: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jsonapi-swagger-0.6.0/lib/generators/jsonapi/swagger/templates/swagger.json.erb:265:in `template'
	 3: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jsonapi-swagger-0.6.0/lib/generators/jsonapi/swagger/templates/swagger.json.erb:7:in `list_resource_parameters'
	 2: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jsonapi-swagger-0.6.0/lib/generators/jsonapi/swagger/templates/swagger.json.erb:7:in `tap'
	 1: from /Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jsonapi-swagger-0.6.0/lib/generators/jsonapi/swagger/templates/swagger.json.erb:10:in `block in list_resource_parameters'
/Users/Will/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/jsonapi-swagger-0.6.0/lib/generators/jsonapi/swagger/swagger_generator.rb:101:in `sortable_fields': undefined method `sortable_fields' for UserResource:Class (NoMethodError)
```

And here is what my user resource looks like:
```
class UserResource < JSONAPI::Serializable::Resource
  type 'users'
  id { @object.uid }

  attributes *[
    :uid,
    :email,
    :created_at,
    :updated_at,
    :admin,
  ]
end
```

**Comment by superiorlu** [comment]
this gem only support [jsonapi-resources](https://github.com/cerebris/jsonapi-resources/)  at present.

**Comment by superiorlu** [comment]
@will3216 you can upgrade `0.7.0`, this version support `jsonapi serializable resource` now.
